server:
  port: 8807
spring:
  application:
    name: sc-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: service-hi
          uri: lb://SERVICE-HI
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1  #defalut path is service name
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
